CREATE TABLE card_history (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    card_id INTEGER NOT NULL REFERENCES card(id),
    column_id INTEGER NOT NULL REFERENCES column(id),
    status VARCHAR(50) NOT NULL,
    moved_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
